const fs=require('fs'),ts=require('typescript'),assert=require('assert/strict');
const source=fs.readFileSync(__dirname+'/../lib/teamRoom.ts','utf8');
const m={exports:{}};new Function('exports',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(m.exports);
const {growthPlayers,goalProgress,roomWeek,weekEnd,safeVideoUrl}=m.exports;
const events=Array.from({length:7},(_,i)=>({id:'e'+i,event_date:'2026-09-'+(21+i),event_time:'22:00'}));
const reports=events.slice(0,6).map(e=>({match_id:e.id,team_score:2,opponent_score:1}));
const ratings=events.map((e,i)=>({match_id:e.id,player_id:'p',rating:i<3?6:8}));
assert.equal(growthPlayers(ratings,events,reports)[0].improvement,2);
assert.equal(growthPlayers([...ratings,{...ratings[0]}],events,reports)[0].improvement,2);
assert.equal(growthPlayers(ratings.slice(0,5),events,reports).length,0);
assert.equal(growthPlayers(ratings.map(r=>({...r,rating:6})),events,reports).length,0);
assert.equal(goalProgress('assists',0,'2026-09-21',events,reports,events.map(e=>({match_id:e.id,goals:3,assists:2}))),12);
assert.equal(goalProgress('goals',0,'2026-09-28',events,reports,[{match_id:'e0',goals:3,assists:2}]),0);
assert.equal(goalProgress('wins',0,'2026-09-21',events,reports,[]),6);
assert.equal(goalProgress('manual',7,'2026-09-21',events,reports,[]),7);
assert.equal(roomWeek(new Date('2026-09-27T23:30:00Z')),'2026-09-28');
assert.equal(weekEnd('2026-09-28'),'2026-10-04');
assert.equal(safeVideoUrl('javascript:alert(1)'),null);
assert.equal(safeVideoUrl('https://example.com/video'),'https://example.com/video');
console.log('PASS: 12 checks, growth deduplication, minimum games, week boundary, objectives, safe links');
